name: ryu-cho

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-jp/ryu-cho@v1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          username: kiaking
          email: "kia.king.08@gmail.com"
          upstream-repo: https://github.com/vuejs-jp/vite-docs-ja.git
          upstream-repo-branch: main
          head-repo: https://github.com/vitejs/vite
          head-repo-branch: main
          track-from: f3643d8e74db07a0c3014987e8c87d4fec31f5a9
          path-starts-with: docs/
          workflow-name: ryu-cho
